// AttributeBegin
// AttributeEnd
// ActiveTransform
// AreaLightSource
// Accelerator
// ConcatTransform
// CoordinateSystem
// CoordSysTransform
// Camera
// Film
// Integrator
// Include
// Identity
// LightSource
// LookAt
// MakeNamedMaterial
// MakeNamedMedium
// Material
// MediumInterface
// NamedMaterial
// ObjectBegin
// ObjectEnd
// ObjectInstance
// PixelFilter
// ReverseOrientation
// Rotate
// Shape
// Sampler
// Scale
// TransformBegin
// TransformEnd
// Transform
// Translate
// TransformTimes
// Texture
// WorldBegin
// WorldEnd

fn main() {
    println!("Hello, world!");
}
